# PLACEHOLDER — generated by nixos-generate-config on the pc
# Replace this file after booting the NixOS installer:
#   nixos-generate-config --show-hardware-config > hardware-configuration.nix
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Will be populated by nixos-generate-config
}
